services:
  # 1. A persistent disk to store your vector database data
  - name: qdrant-disk
    type: pserv
    disk:
      name: qdrant-data
      mountPath: /qdrant/storage
      sizeGB: 1

  # 2. The Qdrant Vector Database
  - name: qdrant-db
    type: pserv
    env: docker
    dockerImage: qdrant/qdrant:latest
    disk:
      name: qdrant-data
      mountPath: /qdrant/storage

  # 3. Redis Instance
  - name: redis
    type: redis
    plan: free

  # 4. FastAPI Web Server (your API)
  - name: api-server
    type: web
    env: docker
    plan: free
    buildCommand: "./build.sh"
    startCommand: "uvicorn main:app --host 0.0.0.0 --port $PORT"
    envVars:
      - key: REDIS_URL
        fromService:
          type: redis
          name: redis
      - key: QDRANT_URL
        fromService:
          type: pserv
          name: qdrant-db
      - key: HF_TOKEN
        sync: false

  # 5. Celery Worker
  - name: celery-worker
    type: worker
    env: docker
    plan: free
    buildCommand: "./build.sh"
    startCommand: "celery -A celery_worker worker --loglevel=info"
    envVars:
      - key: REDIS_URL
        fromService:
          type: redis
          name: redis
      - key: QDRANT_URL
        fromService:
          type: pserv
          name: qdrant-db
      - key: HF_TOKEN
        sync: false
