- name: api-server
  type: web
  plan: free
  env: docker
  buildCommand: ""
  startCommand: ""
  envVars:
    - key: REDIS_URL
      fromService:
        type: redis
        name: redis
    - key: QDRANT_URL
      fromService:
        type: pserv
        name: qdrant-db
    - key: HF_TOKEN
      sync: false
